### ISSUE TITLE
Missing org.dpadgett.timer.R

### ISSUE THREAD

**Issue by dysbulic** [dpadgett/Timer#6]
I import the files into Eclipse using the Existing Android Application filter. I get a bunch of build errors about missing org.dpadgett.timer.R. Cleaning the project doesn't generate it.

**Comment by dpadgett** [comment]
what branch did you use?  head?  the active branch is named "backport".

**Comment by dysbulic** [comment]
I tried release_1.2. I ended up just modeling something off of what you'd done. Thanks for the code.
